main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'news.views.error_404'

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns= [
        path("__debug/__", include(debug_toolbar.urls)), ] + urlpatterns

    urlpatterns +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Административная панель'
admin.site.index_title = 'Административная панель'

main/news/urls.py
from django.urls import path
from . import views

app_name = "news_app"


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('news/', views.ArticleListView.as_view(), name='news_list'),
    path('news/<int:pk>/', views.ArticleDetailView.as_view(), name='single_news'),
    path('update/<int:pk>/', views.ArticleUpdatelView.as_view(), name='update_news'), #корректировка новости
    path('news/add', views.add_news, name='add_news'),                             #добавление новости
    path('delete/<int:pk>/', views.ArticleDeletelView.as_view(), name='delete_news'),      #удаление новости
    path('search_news/', views.search_news, name='search_news'),      #поиск новостей
    path('autosuggest/', views.autosuggest, name='autosuggest'),      #автоподставление
    path("my_news_list/", views.AuthorListView.as_view(), name= "my_news_list"), #список новостей автора
    path("add_tag_category/", views.add_tag_category, name= "add_tag_category"), #список новостей автора


]

main/users/urls.py
from django.urls import path
from . import views

app_name= 'users_app'

urlpatterns = [
    path('', views.user_index, name='user_index'),
    path('contact_page/', views.contact_page, name='contact_page'), #страница обратной связи (зедсь отдельную ссылку)
    path('registration', views.register_request, name="register"), #страница регистрации
    path('user_account/', views.user_account, name='user_account'), #профиль аккаунта
    path("login/", views.login_request, name="login"),  #страница входа в аккаунт
    path("logout/", views.logout_request, name= "logout"), #страница выхода из аккаунта
    path('change_password/', views.change_password, name='change_password'),
    path('favorites/<int:id>', views.add_to_favorites, name='favorites'), #добавление в закладки
    path('profile_delete/', views.profile_delete, name='profile_delete'), #удаление аккаунта
    path("bookmarks/", views.FavoriteArticleListView.as_view(), name= "bookmarks"), #список новостей автора


]

main/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
import shutil
import os



from django.conf import settings

base_dir = settings.MEDIA_ROOT

import datetime
class PublishedToday(models.Manager):
    def get_queryset(self):
        return super(PublishedToday,self).get_queryset().filter(date__gte=datetime.date.today())

class Tag(models.Model):
    title = models.CharField(max_length=15, verbose_name='Название')
    status = models.BooleanField(default=True, verbose_name='Статус')

    def __str__(self):
        return self.title

    def tag_count(self):
        count = self.article_set.count()
        return count

    class Meta:
        ordering = ['title', 'status']
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"



class Article(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Автор')
    title = models.CharField('Название', max_length=50, default='')
    anouncement = models.TextField('Аннотация', max_length=250)
    text = models.TextField('Текст новости')
    date = models.DateTimeField('Дата публикации', auto_now=True) #default=timezone.now
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, verbose_name='Категория')
    tags = models.ManyToManyField(to = Tag, blank=True, verbose_name='Тэги')


    objects = models.Manager()
    published = PublishedToday()

    #date_created = models.DateTimeField(auto_now_add=True)
    #date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Новость: {self.title} от {str(self.date)[:19]}'
    def get_absolute_url(self):
        return f'/news/{int(self.id)}'
    def tag_list(self):
        s = ''
        for tag in self.tags.all():
            s += '*'+tag.title +' '
        return s

    def image_tag(self):
        image = ShowImage.objects.filter(article = self)
        if image:
            return mark_safe(f"<img src='{image[0].image.url}' height='50px' width='auto'/>")
        else:
            return 'No Image'


    def delete(self, *args, **kwargs):
        """для автоматического удаления папки с изображениями статьи"""
        dir_path = f"article_images/article_{self.pk}"
        ar_dir = os.path.join(base_dir, dir_path)
        if os.path.exists(ar_dir):
            shutil.rmtree(ar_dir)

        super(Article, self).delete(*args, **kwargs)

    def get_views(self):
        return self.views.count() #views - это related_name из связанной модели ViewCounter

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"
        ordering = ['title','date']



class Category(models.Model):
    name = models.CharField('Категория', max_length=200,
                            unique=True,
                            )

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"



class ShowImage(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, blank=True)

    def folder_path(instance, filename):
        return f"article_images/article_{instance.article.pk}/{filename}"

    image = models.ImageField(upload_to=folder_path)

    def __str__(self):
        return self.title
    def image_tag(self):
        if self.image is not None:
            return mark_safe(f"<img src='{self.image.url}' height='50px' width='auto'/>")
        else:
            return 'No Image'

##-----------------------Счетчик просмотров_________________________#######################
class ViewCounter(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='views', verbose_name='Счетчик просмотров')
    ip_address = models.GenericIPAddressField()
    view_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-view_date", )
        indexes = [models.Index(fields=["-view_date",])]

    def __str__(self):
        return self.article.title

main/news/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Article, Tag, ShowImage, Category

class MultipleFileInput(forms.ClearableFileInput):
    #для множественного выбора изображений
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    # для множественного выбора изображений
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result




ImagesFormSet = inlineformset_factory(Article, ShowImage, fields=("image",),extra=1,max_num=4,
    widgets={
        "image_field": MultipleFileField(),
    })


class ArticleForm(forms.ModelForm):
    image_field = MultipleFileField()
    class Meta:
        model = Article
        fields = ["title", "anouncement", "text",  "category", "tags"]

        tags = forms.ModelMultipleChoiceField( queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple  )

        widgets = {
            'title': forms.TextInput(attrs={"class": "form-control"}),
            'anouncement': forms.Textarea(attrs={"class": "form-control", "rows": 1}),
            'text': forms.Textarea(attrs={"class": "form-control"}),
            #'image': forms.FileInput(attrs={"class": "form-control"}), #для добавления только одной картинки
            'category': forms.Select(attrs={"class": "form-control"}),
                }


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["title", "status"]

        widgets = {
            'title': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Введите название тэга'}, ),
            'status': forms.CheckboxInput(),
                }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]

        widgets = {'name': forms.TextInput(attrs={"class": "form-control", 'placeholder': 'Введите название категории'},), }

main/news/views.py
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django_filters.views import FilterView
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib import messages


from .forms import ArticleForm, ImagesFormSet, TagForm, CategoryForm
from .models import Article, ShowImage, Tag, Category
from .filters import ArticleFilter
from users.utils import check_group
from .utils import ViewCountMixin


from users.models import FavoriteArticle


def index(request):
    articles = Article.objects.all().order_by("-date")
    p = Paginator(articles, 3)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)

    bookmarks = FavoriteArticle.objects.filter(user=request.user.id).values_list('article_id', flat=True)


    context = {'posts': page_obj, 'articles':  articles, 'bookmarks': bookmarks}
    return render(request, 'news/index.html', context)



def about(request):
    return render(request, 'news/about.html' )


def error_404(request, exception):
    "функция вызова ошибки 404"
    context = {}
    return render(request, 'news/404.html', context)


##-----------------------Добавление новости_________________________#######################
@check_group('Авторы')
@login_required(login_url='users_app:login')
def add_news(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            if current_user.id:
                new_article = form.save(commit=False)
                new_article.author = current_user
                new_article.save()
                form.save_m2m() #чтобы сохранилась связь многие-ко-многим
                for img in request.FILES.getlist('image_field'):
                    ShowImage.objects.create(article=new_article, image= img, title=img.name)
                return redirect(new_article)
    else:
        form = ArticleForm()
    return render(request, 'news/add_news.html', {"form": form})

##-----------------------Просмотр одной новости_________________________#######################
class ArticleDetailView(ViewCountMixin,DetailView):
    model = Article
    template_name = 'news/single_news.html'
    context_object_name = 'article'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_object = self.object
        images = ShowImage.objects.filter(article = current_object)
        bookmark = FavoriteArticle.objects.filter(user=self.request.user.id, article_id=current_object.id)
        context['images'] = images
        context['bookmark'] = bookmark
        return context




##-----------------------Обновление новости_________________________#######################
class ArticleUpdatelView(UpdateView):
    model = Article
    template_name = 'news/add_news.html'
    fields = ['title', 'anouncement', 'text', 'category',  'tags']
    #success_url = reverse_lazy('news_app:news_list')

    def get(self, request, **kwargs):
        self.object = self.get_object()
        if self.request.user.id != self.object.author.id and (not self.request.user.is_staff):
            messages.error(request, "Ошибка доступа")
            return HttpResponseRedirect(self.object.get_absolute_url())
        else:
            context = self.get_context_data(object=self.object)
            return self.render_to_response(context)








class ArticleDeletelView(DeleteView):
    model = Article
    success_url = reverse_lazy('news_app:news_list')
    template_name = 'news/delete_news.html'

    def get(self, request, **kwargs):
        self.object = self.get_object()
        if self.request.user.id != self.object.author.id and (not self.request.user.is_staff):
            messages.error(request, "Ошибка доступа")
            return HttpResponseRedirect(self.object.get_absolute_url())
        else:
            context = self.get_context_data(object=self.object)
            return self.render_to_response(context)




from .utils import ArticleTable
from django_tables2 import SingleTableView, SingleTableMixin


##-----------------------Фильтрация новостей_________________________#######################
class ArticleListView(SingleTableMixin,FilterView):
    model = Article
    table_class = ArticleTable
    filterset_class = ArticleFilter
    paginate_by = 15
    template_name = 'news/news.html'



def search_news(request):
    """страница поиска новости по заголовку и аннотации"""
    search_post = request.GET.get("search")
    if search_post:
        posts = Article.objects.filter(
            Q(title__icontains=search_post) | Q(anouncement__icontains=search_post))  # | Q(text__icontains=search_post)
    else:
        posts = Article.objects.all().order_by("-date")

    context = {'posts': posts}
    return render(request, 'news/search.html', context)



##-----------------------Jquery Автозаполнение _________________________#######################
def autosuggest(request):
    query_original = request.GET.get('term')
    qs = Article.objects.filter(title__icontains=query_original)
    results = []
    results += [article.title for article in qs]
    return JsonResponse(results, safe=False)

##-----------------------Search Component in Navbar _________________________#######################
def search_news(request):
    search_post = request.GET.get("search", None)
    if search_post:
        search_query = search_post.lower().split()
        lookups = Q()
        for word in search_query:
            lookups |= Q(title__icontains=word)
        posts = Article.objects.filter(lookups)
    else:
        posts = Article.objects.all().order_by("-date")

    context = {'posts': posts}

    return render(request,'news/search.html', context)



##-----------------------Список новостей автора_________________________#######################
class AuthorListView(SingleTableMixin,FilterView):

    def get_queryset(self):
        qs = Article.objects.filter(author=self.request.user)
        return qs


    model = Article
    table_class = ArticleTable
    filterset_class = ArticleFilter
    paginate_by = 15
    template_name = 'news/my_news_list.html'


##-----------------------Добавление Тэгов и Категорий_________________________#######################
@check_group('Авторы')
@login_required(login_url='users_app:login')
def add_tag_category(request):
    tag = Tag.objects.all()
    category = Category.objects.all()
    if request.method == 'POST':
        tag_form = TagForm(request.POST)
        category_form = CategoryForm(request.POST)
        if tag_form.is_valid():
            new_tag = tag_form.save(commit=False)
            new_tag.save()
            tag_form.save_m2m() #чтобы сохранилась связь многие-ко-многим
            messages.success(request, f"Новый тэг {new_tag.title} успешно создан")
            return HttpResponseRedirect(request.META['HTTP_REFERER'])

        if category_form.is_valid():
            new_category = category_form.save()
            messages.success(request, f"Новая категория {new_category.name} успешно создана")
            return HttpResponseRedirect(request.META['HTTP_REFERER'])

    else:
        tag_form = TagForm()
        category_form = CategoryForm()
    return render(request, 'news/add_category.html', {"tag_form": tag_form, "category_form": category_form,
                                                      "tags": tag, "category": category})

main/news/templates/news/about.html
{% extends "news/base_generic.html" %}
{% load static %}

<link rel="stylesheet" href="{% static 'news/css/styles.css'  %}">

{% block title %} О нас {% endblock %}


{% block content %}



<div class="login_info">
        <h1>здесь будет информация о редакторах сайта</h1>
</div>



{% endblock content %}

main/news/templates/news/header.html
<!doctype html>
<html lang="en">

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load bootstrap_icons %}
{% load static %}

{% load users_extras %}


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--скрипты ниже для работы выпадающего меню пользователя-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />

    <!-- jQuery autocomplete CSS -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">


<!-- jQuery
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>

<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
!-->

</head>

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>



 <script>
      $( function() {
        $( "#search_input" ).autocomplete({
          source: "{% url 'news_app:autosuggest' %}",
          minLength:1
        });
      });
    </script>




  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'news_app:index' %}"> <img src="{% static 'news/img/logo.png' %}" /> </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item px-3">
                        <a class="nav-link active" aria-current="page" href="{% url 'news_app:news_list' %}">Новости</a>
                    </li>
                    <li class="nav-item px-3">
                        <a class="nav-link active" href="{% url 'users_app:contact_page' %}">Обратная связь</a>
                    </li>
                </ul>




                <!--поле поиска-->
                <form class="d-flex" style="height: 60px;" role="search" action="{% url 'news_app:search_news' %}">
                    <input class="form-control me-2" type="search" id="search_input" placeholder="Найти" aria-label="Search" name="search" />
                    <button class="btn btn-outline-secondary text-black" type="submit">Поиск новостей</button>
                </form>




                <!--выпадающее меню пользователя-->
                {% if user.is_authenticated %}  <!--Если пользователь авторизован-->
                <div class="dropdown px-4">

                    <button class="btn btn-outline-secondary dropdown-toggle text-black" type="button" style="height: 60px;" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{request.user.username}}
                    </button>



                    {% if request.user|has_group:"Авторы" or user.is_staff  %} <!--Если пользователь Автор или Персонал-->

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'news_app:add_news' %}">Создать статью</a></li>
                        <li><a class="dropdown-item" href="{% url 'news_app:my_news_list' %}">Мои статьи</a></li>
                        <li><a class="dropdown-item" href="{% url 'users_app:bookmarks' %}">Избранное</a></li>
                        <li><a class="dropdown-item" href="{% url 'news_app:add_tag_category' %}">Добавить тэг</a></li>
                            {% if request.user.is_staff  %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ. панель</a></li>
                            {% endif %}

                        <li><a class="dropdown-item" href="{% url 'users_app:user_account' %}">Личный кабинет</a></li>
                        <li><a class="dropdown-item" href="{% url 'users_app:logout' %}">Выйти</a></li>
                    </ul>



                    {% else %} <!--Если пользователь Читатель-->

                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="#">Избранное</a></li>
                        <li><a class="dropdown-item" href="{% url 'users_app:user_account' %}">Личный кабинет</a></li>
                        <li><a class="dropdown-item" href="{% url 'users_app:logout' %}">Выйти</a></li>
                    </ul>

                {% endif %}

                </div>


                {% else %} <!--Для не авторизованного пользователя-->
                <div class="dropdown px-4">
                    <button class="btn btn-outline-secondary dropdown-toggle text-black" type="button" style="height: 60px;" id="dropdownMenuButton2" data-bs-toggle="dropdown">Профиль пользователя</button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                        <li><a class="dropdown-item" href="{% url 'users_app:login' %}">Войти</a></li>
                        <li><a class="dropdown-item" href="{% url 'users_app:register' %}">Регистрация</a></li>
                    </ul>
                </div>
                {% endif %}

            </div>
        </div>
    </nav>
</body>
</html>

main/news/templates/news/search.html
{% extends "news/base_generic.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'news/css/styles.css'  %}">

{% block title %}
  Страница поиска
{% endblock %}

{% block content %}
<!--поле поиска-->
<div class="container-fluid text-center" style="border:2px solid #cecece; background-color: #FAEBD7!important">
    <form class="my-2 my-lg-0" role="search" action="{% url 'news_app:search_news' %}" method="get">
        <input class="form-control me-2 mt-3" type="search" placeholder="Найти" aria-label="Search" name="search">
        <button class="btn btn-outline-secondary text-black btn-lg mt-2 mb-2" type="submit">Найти</button>
    </form>
</div>

<!--поле с количеством найденных записей-->
<div class="search_result m-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <br>
                <p class="lead">Найдено записей: {{ posts.count }} </p>
            </div>
        </div>
    </div>
</div>

<!--поле с найденныими новостями-->
<div class="container-fluid">
    {% for article in posts %}
    <div class="single_news m-3">
        <div class="p-2 p-md-15 text-white rounded bg-dark">
            <div class="col-md-6 px-5">
                <h1 class="display-4 fst-italic"> {{ article.title }}</h1>
                <p class="lead my-3">Автор: {{ article.author }}</p>
                <p class="lead my-3">Дата создания: {{ article.date }}</p>
                <p class="lead mb-0"><a href="{{ article.get_absolute_url }}" class="text-white fw-bold"> Читать полностью...</a></p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

main/news/templates/news/single_news.html
{% extends  'news/base_generic.html' %}

{% load bootstrap5 %}
{% load bootstrap_icons %}
{% load static %}
{% load widget_tweaks %}

{% block title %} Новость {{ article.id }} {% endblock title %}
<head>





</head>

{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


<div class="container mt-3">

             <div class="single_news">
                <div class="p-4 p-md-5 text-white rounded bg-dark" >
                        <div class="col-md-12 px-0">
                          <h1 class="display-4 fst-italic"> {{ article.title }}</h1>
                            <br> <br>

                            <!-- Карусель -->
                            {% if article.showimage_set.all %}
                           <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" data-interval="false">
                              <div class="carousel-inner" role="listbox" style="width: auto%; height: 480px; !important;">

                                  {% for image in article.showimage_set.all %}
                                    <div class="carousel-item {%if forloop.counter == 1%}active{% endif%}">
                                      <img class="d-block" style="width: 100%; height: 100%; border-radius:5px;" src="{{image.image.url}}" alt="First slide">
                                    </div>
                                  {% endfor %}
                                </div>

                              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                              </a>
                              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                              </a>
                           </div>
                            {% endif%}

                            <br> <br>


                          <p class="lead mt-2">Новость: <p style="font-family: Serif; font-size: 20px; "> {{ article.text }} </p> </p>
                          <p class="lead mt-2">Автор: {{ article.author }}</p>
                          <p class="lead mt-2">Теги: {% for t in article.tags.all %} {{ t.title }} {% endfor %}</p>
                        </div>
                <br> <br>

                {% if request.user.is_authenticated %}
                    {% if request.user.id == article.author.id  or request.user.is_staff %}
                        <a class="btn btn-danger" href="{% url 'news_app:delete_news' article.pk%}">Удалить новость</a>
                        <a class="btn btn-primary" href="{% url 'news_app:update_news' article.pk%}">Редактировать</a>
                            {% if request.user.is_staff %}
                                {% if bookmark %}
                                    <a class="btn btn-warning" href="{% url 'users_app:favorites' article.pk %}"><i class="fa fa-bookmark">Удалить из избранного</i></a>
                                {% else %}
                                    <a class="btn btn-success" href="{% url 'users_app:favorites' article.pk %}"><i class="fa fa-bookmark">В избранное</i></a>
                                {% endif %}

                            {% endif %}

                    {% else %}
                        <a class="btn btn-secondary disabled">Удалить</a>
                        <a class="btn btn-secondary disabled">Редактировать</a>
                        {% if bookmark %}
                                <a class="btn btn-warning" href="{% url 'users_app:favorites' article.pk %}"><i class="fa fa-bookmark">Удалить из избранного</i></a>
                            {% else %}
                                <a class="btn btn-success" href="{% url 'users_app:favorites' article.pk %}"><i class="fa fa-bookmark">В избранное</i></a>
                             {% endif %}
                   {% endif %}
                {% endif %}
                </div>
            </div>
        </div>

{% endblock content %}