main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'news.views.error_404'

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns= [
        path("__debug/__", include(debug_toolbar.urls)), ] + urlpatterns

    urlpatterns +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Административная панель'
admin.site.index_title = 'Административная панель'

main/news/urls.py
from django.urls import path
from . import views

app_name = "news_app"


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('news/', views.ArticleListView.as_view(), name='news_list'),
    path('news/<int:pk>/', views.ArticleDetailView.as_view(), name='single_news'),
    path('update/<int:pk>/', views.ArticleUpdatelView.as_view(), name='update_news'), #корректировка новости
    path('news/add', views.add_news, name='add_news'),                             #добавление новости
    path('delete/<int:pk>/', views.ArticleDeletelView.as_view(), name='delete_news'),      #удаление новости
    path('search_news/', views.search_news, name='search_news'),      #поиск новостей
    path('autosuggest/', views.autosuggest, name='autosuggest'),      #автоподставление
    path("my_news_list/", views.AuthorListView.as_view(), name= "my_news_list"), #список новостей автора
    path("add_tag_category/", views.add_tag_category, name= "add_tag_category"), #список новостей автора


]

main/users/urls.py
from django.urls import path
from . import views

app_name= 'users_app'

urlpatterns = [
    path('', views.user_index, name='user_index'),
    path('contact_page/', views.contact_page, name='contact_page'), #страница обратной связи (зедсь отдельную ссылку)
    path('registration', views.register_request, name="register"), #страница регистрации
    path('user_account/', views.user_account, name='user_account'), #профиль аккаунта
    path("login/", views.login_request, name="login"),  #страница входа в аккаунт
    path("logout/", views.logout_request, name= "logout"), #страница выхода из аккаунта
    path('change_password/', views.change_password, name='change_password'),
    path('favorites/<int:id>', views.add_to_favorites, name='favorites'), #добавление в закладки
    path('profile_delete/', views.profile_delete, name='profile_delete'), #удаление аккаунта
    path("bookmarks/", views.FavoriteArticleListView.as_view(), name= "bookmarks"), #список новостей автора


]

main/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

from django.dispatch import receiver
from django.db.models.signals import post_save

class Account(models.Model):
    gender_choices = (
        ('M', 'Мужской'),
        ('Ж', 'Женский'),
        ('Н/Д', 'не указано')
            )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, verbose_name='Пользователь')
    birthdate = models.DateField( verbose_name="Дата рождения", null=True,)
    gender = models.CharField(choices=gender_choices, max_length=20, verbose_name="Пол")

    def folder_path(instance, filename):
        return f"account_images/{instance.user.username}/{filename}"

    account_image = models.ImageField(default='account_images/default_account.png', upload_to=folder_path, verbose_name="Изображение профиля")

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.account_image.path)

        if img.height > 100 or img.width > 100:
            new_img = (500, 500)
            img.thumbnail(new_img)
            img.save(self.account_image.path)

    def __str__(self):
        return f"{self.user.username}'s account"

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Account.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.account.save()



    class Meta:
        verbose_name = "Аккаунт"
        verbose_name_plural = "Аккаунты"






from news.models import Article
class FavoriteArticle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True )
    create_at = models.DateTimeField(auto_now_add=True)

main/users/forms.py
from django import forms
from django.contrib.auth import update_session_auth_hash
from django.core.validators import MinLengthValidator

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.http import JsonResponse

from .models import Account


from django.forms.widgets import NumberInput

class ContactForm(forms.Form):
	#форма обратной связи

    name = forms.CharField(max_length=40,label='Имя пользователя', validators= [MinLengthValidator(2)], disabled=True)
    email = forms.EmailField(label='Email', disabled=True)
    message = forms.CharField(max_length=100, label='Введите сообщение',
                              widget=forms.Textarea)



def validate_email(value):
    if User.objects.filter(email = value).exists():
        raise forms.ValidationError("Такой адрес электронный почты уже используется!")



class UserForm(UserCreationForm):
	# форма регистрации нового пользователя
	username = forms.CharField(label="Логин")
	email = forms.EmailField(required=True, validators = [validate_email])
	password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput)
	password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name', "password1", "password2")

		def save(self, commit=True):
			user = super(UserForm, self).save(commit=False)
			user.email = self.cleaned_data['email']
			if commit:
				user.save()
			return user



class ProfileForm(forms.ModelForm):
	#форма обновления данных профиля

	class Meta:
		model = Account
		fields = ('birthdate', 'gender', 'account_image')
		widgets = {
					'birthdate': NumberInput(attrs={'type': 'date'})
		}

class UserUpdateForm(UserChangeForm):
	# форма обновления данных класса User
	password = None
	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name', )

main/users/views.py
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.urls import reverse_lazy
from django.core.paginator import Paginator


from .models import Account, FavoriteArticle
from .forms import ContactForm, ProfileForm, UserForm, UserUpdateForm
from .utils import check_group



def user_index(request):
    try:
        user_acc =Account.objects.get(user = request.user)
        return HttpResponse(
            f"Приложение USERS, {request.user} | {request.user.id} | {user_acc.nickname}, {request.GET}")
    except:
        return HttpResponse('не авторизован')



##-----------------------Страница обратной связи(только для авторизованных)_________________________#######################
@check_group()
def contact_page(request):
    if request.method == "POST":
        form = ContactForm(request.POST, initial={'email': request.user.email, 'name':request.user.username})
        if form.is_valid():
            print(form.cleaned_data)
            messages.success(request, ('Сообщение отправлено'))
            return redirect("users_app:contact_page")
        else:
            print('Ошибка', form.errors)

    else:
        form = ContactForm(initial={'email': request.user.email, 'name':request.user.username})
    us = request.user

    context = {'form': form, 'user': us}
    return render(request, 'users/contact_page.html', context)



##-----------------------Регистрация нового пользователя_________________________#######################
def register_request(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            category = request.POST['account_type']

            if category == 'author':
                group = Group.objects.get(name='Необходимо утверждение')
                user.groups.add(group)
            else:
                group = Group.objects.get(name='Читатель')
                user.groups.add(group)

            login(request, user)
            return redirect("users_app:user_account")
        else:
            messages.error(request, "Не удалось зарегистрировать пользователя")
    else:
        form = UserForm()

    context = {'form': form}
    return render(request, "users/registration.html", context)





##-----------------------Обновление профиля_________________________#######################
@login_required(login_url='users_app:login', )
def user_account(request):

    if request.method == "POST" and 'changing_profile' in request.POST:
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.account)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Данные профиля обновлены'))
            return HttpResponseRedirect(request.path_info)

        """else:
            messages.error(request, ('Unable to complete request'))"""

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.account)


    return render(request=request, template_name="users/user_profile.html",
                  context={"user": request.user, "user_form": user_form, "profile_form": profile_form})



def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Ваш пароль успешно изменен')
            return redirect('users_app:user_account')
        else:
            messages.error(request, 'Неправильно введены данные')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'users/change_password.html', {
        'password_form': form})







##-----------------------Авторизация_________________________#######################
def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Вы вошли в аккаунт {username}")
                return redirect("users_app:user_account")
            else:
                messages.error(request, "Неправильное имя пользователя или пароль")
        else:
            messages.error(request, "Неправильное имя пользователя или пароль")
    form = AuthenticationForm()
    return render(request=request, template_name="users/login.html", context={"login_form": form})


##-----------------------Выход из профиля_________________________#######################
def logout_request(request):
    logout(request)
    messages.info(request, "Вы вышли из аккаунта")
    return redirect("news_app:index")


##-----------------------Удаление аккаунта_________________________#######################
@login_required
def profile_delete(request):
    user = request.user
    user.delete()
    messages.info(request, "Аккаунт удален")
    return redirect("news_app:index")




from news.models import Article

##-----------------------Добавить в избранное_________________________#######################
@login_required
def add_to_favorites(request, id):
    article = Article.objects.get(id=id)
    bookmark = FavoriteArticle.objects.filter(user = request.user.id, article = article)

    if bookmark.exists():
        bookmark.delete()
        messages.warning(request, 'Закладка удалена')

    else:
        bookmark = FavoriteArticle.objects.create(user = request.user, article=article)
        messages.success(request, 'Добавлено в избранное')
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

    total = len(articles)
    p = Paginator(articles,2)
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)

    context = {'articles': page_obj, 'total':total, 'bookmark':bookmark }
    #           'categories':categories,'selected_category': selected_category}

    return render(request,'users/my_news_list.html',context)





from news.utils import ArticleTable
from news.filters import ArticleFilter
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView

##-----------------------Избранные новости_________________________#######################
class FavoriteArticleListView(SingleTableMixin,FilterView):
    model = Article
    table_class = ArticleTable
    filterset_class = ArticleFilter
    paginate_by = 15
    template_name = 'users/my_favorite.html'

    def get_queryset(self):
        bookmark_id = FavoriteArticle.objects.filter(user=self.request.user.id).values_list('article_id', flat=True)
        favorite_article = Article.objects.filter(id__in=bookmark_id)
        return favorite_article

main/users/templates/users/change_password.html
{% extends  'news/base_generic.html' %}

{% load bootstrap5 %}
{% load crispy_forms_tags %}


{% block content %}


<!--Login-->
 <div class="container py-5">
        <h1>Смена пароля</h1> <br> <br>

        <form method="POST">
		{% csrf_token %}
		{{ password_form|crispy }}
		<button class="btn btn-primary" type="submit">Сохранить изменения</button>
	    </form>


    </div>


{% endblock %}

main/users/templates/users/contact_page.html
{% extends  'news/base_generic.html' %}

{% load bootstrap5 %}
{% load static %}
{% load widget_tweaks %}

{% load crispy_forms_tags %}

{% block title %} Обратная связь {% endblock title %}



{% block content %}

    <div class="container-fluid">
         <div class="text-center">
             <h1>Страница обратной связи</h1>


             <form method="post" class="contact_form">
                {% csrf_token %}
                {{ form|crispy }}
                {% comment %} {% for field in form  %}

                 {{ field.label_tag}} {% render_field field class="form-control" %}
                    {% if field.label == "Имя пользователя" or field.label == "Email" %}
                        {{field.disabled}}
                    {% endif %}
                {% endfor %}
                {% endcomment  %}

                <input type="submit"  class="btn btn-success" value="Отправить">
            </form>

         </div>


    </div>


{% endblock %}

main/users/templates/users/login.html
{% extends  'news/base_generic.html' %}

{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}

{% block title %} Вход в аккаунт {% endblock title %}



{% block content %}

 <!--Login-->
 <div class="container py-5">
        <h1> Вход в аккаунт</h1> <br> <br>

        <form method="POST">
		{% csrf_token %}
		{{ login_form|crispy }}
		<button class="btn btn-primary" type="submit">Войти</button>
	    </form>

        <p class="text-center">У вас еще нет аккаунта? <a href="{% url 'users_app:register' %}">Зарегистрироваться</a></p>




    </div>


{% endblock %}

main/users/templates/users/my_favorite.html
{% extends  'news/base_generic.html' %}

{% load bootstrap5 %}
{% load bootstrap_icons %}
{% load static %}
{% load widget_tweaks %}
{% load sorting_tags %}
{% load render_table from django_tables2 %}
{% load i18n %}
{% load crispy_forms_tags %}



{% block title %} Избранное {{ article.id }} {% endblock title %}

{% block content %}


<!-- Фильтры для поиска  -->
<div class="container-fluid">
    <div class="col-md-3">
        <div class="container">
            <a class="text-dark text-sm mb-1" href="{% url 'users_app:bookmarks' %}">x Очистить фильтры</a>
            <form action="" method="get">
                <div style="display: grid;">
                    <!-- widget_tweaks -->
                     {% for field in filter.form %}
                     <div id="form-field-{{ forloop.counter0 }}">

                        {% if field.label != "Авторы" %}

                        {{ field.label_tag }} {% render_field field class="form-control" %}
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-primary mb-3 mt-2">Найти</button>
            </form>
        </div>
        <br />
    </div>
</div>




{% if table.rows|length == 0  %}
    <div class="container-fluid">
        <div class="text-center" style="margin-top: 10%;">
            <h1>У вас еще нет избранных новостей</h1>
             <h3><a href="{% url 'news_app:index' %}">Перейти</a> к просмотру новостей</h3>
        </div>
    </div>
{% else %}
    {% render_table table %}
{% endif %}





{% endblock  %}

main/users/templates/users/registration.html
{% extends  'news/base_generic.html' %}

{% load crispy_forms_tags %}

{% block title %} Регистрация {% endblock title %}



{% block content %}

    <div class="container py-5">
        <h1>Регистрация</h1> <br> <br>


        <form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
        <div class="form-check">
            <h5>Тип аккаунта: </h5>
            <div>
                <input class="form-check-input" type="radio" id="author" name="account_type" value="author"/>
                <label class="form-check-label" for="author">Автор</label>
            </div>
            <div>
                <input class="form-check-input" type="radio" id="reader" name="account_type" value="reader"/>
                <label class="form-check-label" for="reader">Читатель</label>
            </div>



        </div>

		<button class="btn btn-primary mt-2" type="submit">Зарегистирироваться</button>
	    </form>

        <p class="text-center">Если у вас уже есть аккаунт,  <a href="{% url 'users_app:login' %}">войдите</a> в учётную запись.</p>




    </div>

{% endblock %}

main/users/templates/users/user_profile.html
{% extends  'news/base_generic.html' %}

{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load i18n widget_tweaks %}
{% load i18n %}


{% block title %} Личный кабинет {% endblock title %}


{% block content %}




<!--Окно данных пользователя-->
<div class="container-fluid">
    <div class="text-center" style="margin-top: 30px;">
        <h2>Редактирование профиля {{ request.user.username }}</h2>
        <br/>

        <div class="d-flex justify-content-center">
            <div class="card">
                <h4 class="card-title font-weight-bold text-center mt-3 fst-italic">Добро пожаловать, {{ user.username }}</h4>
                <hr />

                <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{ request.user.account.account_image.url }}" alt="{{ request.user.username }}" class="rounded-circle" width="150" />
                    {{ account_form.account_image }}
                </div>
                <br />
                <div class="card-text">
                    <p class="text-muted mb-0" style="font-size: 12px font-weight: 700">Логин:</p>
                    <p>{{ user.username }}</p>
                    <p class="text-muted mb-0" style="font-size: 12px font-weight: 700">Имя:</p>
                    <p>{{ user.first_name }} {{ user.last_name }}</p>
                    <p class="text-muted mb-0" style="font-size: 12px font-weight: 700 ">Электронная почта:</p>
                    <p>{{ user.email }}</p>

                    <!-- Button trigger modal -->
                    <div class="text-center">
                        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#profileModal" style="width: 50%; ">Редактировать профиль</button>
                    </div>
                    <br>


                        <div class="text-center">
                            <a class="btn btn-outline-primary" href="{% url 'users_app:change_password' %}" style="width: 50%; ">Сменить пароль</a>
                        </div>
                     <br>


                    <div class="text-center">
                            <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#deleteModal" style="width: 50%; ">Удалить аккаунт</button>
                        </div>
                    <br>

                </div>
            </div>
        </div>
    </div>
</div>



<!--Всплывающее окно редактирования профиля-->
<div class="modal fade" tabindex="-2" id="profileModal" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Редактировать профиль</h5>

            </div>

            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %} {{ user_form|crispy }} {{ profile_form|crispy }}


                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" name="changing_profile">Сохранить изменения</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




<!--Всплывающее окно удаления профиля-->
<div class="modal fade" tabindex="-2" id="deleteModal" aria-hidden="true" role="dialog">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Удалить профиль</h5>
            </div>

            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %}
                    <h3>Вы точно хотите удалить аккаунт {{ request.user.username }}?</h3>

                    <div class="modal-footer">
                        <a class="btn btn-outline-primary" href="{% url 'users_app:profile_delete' %}">Удалить аккаунт</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отменить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock %}